NewGood/Controllers/BlogController.cs
using NewGood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace NewGood.Controllers
{
    public class BlogController : SurfaceController
    {
        public ActionResult RenderPostList(int numberOfItems)
        {
            List<BlogPostList> model = new List<BlogPostList>();
            IPublishedContent blogPage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "blog").FirstOrDefault();

            foreach (IPublishedContent page in blogPage.Children.OrderByDescending(x => x.UpdateDate).Take(numberOfItems))
            {

                //string name = page.GetPropertyValue<string>("title") or:

                string name = page.Name;
                string introduction = page.GetPropertyValue<string>("articleIntro");

                //imageUrl
                int imageId = page.GetPropertyValue<int>("articleImage");
                //gets the value of media picker
                var mediaItem = Umbraco.Media(imageId);
                string imageUrl = mediaItem.Url;

                //linkUrl
                string linkUrl = page.Url;


                model.Add(new BlogPostList(name, introduction, imageUrl, linkUrl));
            }
            return PartialView("~/Views/Partials/Blog/_PostList.cshtml", model);
        }
    }
}

NewGood/Controllers/GuideController.cs
using Archetype.Models;
using NewGood.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace NewGood.Controllers
{
    public class GuideController : SurfaceController
    {
        public ActionResult RenderGuide()
        {
            List<GuideItem> model = new List<GuideItem>();
            IPublishedContent guidePage = CurrentPage.AncestorOrSelf("guide");

            ArchetypeModel guideItems = guidePage.GetPropertyValue<ArchetypeModel>("guideItems");

            foreach (ArchetypeFieldsetModel fieldset in guideItems)
            {

                string category = fieldset.GetValue<string>("category");
                string description = fieldset.GetValue<string>("description");

                model.Add(new GuideItem(category, description));
            }
            return PartialView("~/Views/Partials/Guide/_Guide.cshtml", model);
        }
    }
}

NewGood/Controllers/HomeController.cs
using NewGood.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using System.Linq;
using Archetype;
using Archetype.Models;

namespace NewGood.Controllers
{
    public class HomeController : SurfaceController
    {
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/Home/{name}.cshtml";
        }
        public ActionResult RenderBanner()
        {
            return PartialView(PartialViewPath("_Banner"));
        }

        public ActionResult RenderIntro()
        {
            return PartialView(PartialViewPath("_Intro"));
        }

        public ActionResult RenderFeatured()
        {
            List<FeaturedItem> model = new List<FeaturedItem>();
            //IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");

            //Get property from the homepage
            //From ArchetypeMode model get all the fieldsets and put them into FeaturedItem class
            ArchetypeModel featuredItems = homePage.GetPropertyValue<ArchetypeModel>("featuredItems");

            foreach (ArchetypeFieldsetModel fieldset in featuredItems)
            {

                string name = fieldset.GetValue<string>("name");
                string category = fieldset.GetValue<string>("category");

                //imageUrl
                int imageId = fieldset.GetValue<int>("image");
                //gets the value of media picker
                var mediaItem = Umbraco.Media(imageId);
                string imageUrl = mediaItem.Url;


                //linkUrl
                int pageId = fieldset.GetValue<int>("page");
                IPublishedContent page = Umbraco.TypedContent(pageId);
                string linkUrl = page.Url;


                model.Add(new FeaturedItem(name, category, imageUrl, linkUrl));
            }
            return PartialView(PartialViewPath("_Featured"), model);
        }

        public ActionResult RenderBlog()
        {

            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");

            string title = homePage.GetPropertyValue<string>("blogPreviewTitle");
            string introduction = homePage.GetPropertyValue("blogPreviewIntro").ToString();

            BlogPreview model = new BlogPreview(title, introduction);

            return PartialView(PartialViewPath("_Blog"), model);
        }

        public ActionResult RenderTestimonials()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");

            string title = homePage.GetPropertyValue<string>("testimonialsTitle");
            string introduction = homePage.GetPropertyValue("testimonialsIntro").ToString();

            List<Testimonial> testimonials = new List<Testimonial>();
            ArchetypeModel testimonialsList = homePage.GetPropertyValue<ArchetypeModel>("testimonialsList");
            if (testimonialsList != null)
            {
                foreach (ArchetypeFieldsetModel testimonial in testimonialsList.Take(2))
                {

                    string name = testimonial.GetValue<string>("name");
                    string quote = testimonial.GetValue<string>("quote");

                    testimonials.Add(new Testimonial(name, quote));
                }
            }

            Testimonials model = new Testimonials(title, introduction, testimonials);
            return PartialView(PartialViewPath("_Testimonials"), model);
        }
    }
}

NewGood/Controllers/SiteLayoutController.cs
using System;
using NewGood.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using System.Linq;
using System.Runtime.Caching;

namespace NewGood
{
    public class SiteLayoutController : SurfaceController
    {
        private string PartialViewPath(string name)
        {
            return $"~/Views/Partials/SiteLayout/{name}.cshtml";
        }
        /// <summary>
        /// Renders the header partial with navigation
        /// </summary>
        /// <returns>Partial view with a model</returns>

        public ActionResult RenderHeader()
        {
            // when renderheader is called it calls GetNavigationModelFromDatabase() method
            //List<NavigationListItem> nav = GetNavigationModelFromDatabase();

            // use the model from the cache instead of db
            List<NavigationListItem> nav = GetObjectFromCache<List<NavigationListItem>>("mainNav", 0, GetNavigationModelFromDatabase);
            return PartialView(PartialViewPath("_Header"), nav);

        }

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            //const int HOME_PAGE_POSITION_IN_PATH = 1;
            //int homePageId = int.Parse(CurrentPage.Path.Split(',')[HOME_PAGE_POSITION_IN_PATH]);
            //IPublishedContent homePage = Umbraco.Content(homePageId);
            //IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible").Where(x => x.Level <= 2);
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        /// <summary>
        /// A generic function for getting and setting objects to the memory cache.
        /// </summary>
        /// <typeparam name="T">The type of the object to be returned.</typeparam>
        /// <param name="cacheItemName">The name to be used when storing this object in the cache.</param>
        /// <param name="cacheTimeInMinutes">How long to cache this object for.</param>
        /// <param name="objectSettingFunction">A parameterless function to call if the object isn't in the cache and you need to set it.</param>
        /// <returns>An object of the type you asked for</returns>
        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];
            if (cachedObject == null)
            {
                CacheItemPolicy policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }
            return cachedObject;
        }

        public ActionResult RenderTitle()
        {
            return PartialView(PartialViewPath("_Title"));
        }
        public ActionResult RenderFooter()
        {
            return PartialView(PartialViewPath("_Footer"));
        }
    }
}

NewGood/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}
<div id="fh5co-about-section">
    <div class="container">
       @{ Html.RenderAction("RenderTitle", "SiteLayout");}
       @CurrentPage.GetGridHtml("contentGrid")
    </div>
</div>

NewGood/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}
	<div id="fh5co-blog-section">
		<div class="container">
			@{ Html.RenderAction("RenderTitle", "SiteLayout");}
		    @{ Html.RenderAction("RenderPostList", "Blog", new { numberOfItems  = 6});}
		</div>
	</div>

NewGood/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

<div id="fh5co-about-section">
    <div class="container">
       @{ Html.RenderAction("RenderTitle", "SiteLayout");}
       @CurrentPage.GetGridHtml("contentGrid");
    </div>
</div>

NewGood/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

 <div id="fh5co-featured-section">
        <div class="content">
         <section class="banner banner-img">
                <div class="centered">
                    <h2 class="banner-heading">Good4you</h2>
                    <p class="banner-text">
                        @Umbraco.GetDictionaryValue("Contact.Mobile")<br>
                        @Umbraco.GetDictionaryValue("Contact.EmailOffice")<br>
                        @Umbraco.GetDictionaryValue("Contact.EmailGmail")</p>
                </div><!-- .centered -->
            </section><!-- .banner -->
        </div>
    </div>

NewGood/Views/Guide.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}
<div id="fh5co-main-services-section">
    <div class="container">
        @{ Html.RenderAction("RenderTitle", "SiteLayout");}
        @{ Html.RenderAction("RenderGuide", "Guide");}
    </div>
</div>

NewGood/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@{  Html.RenderAction("RenderBanner", "Home");}

@{  Html.RenderAction("RenderIntro", "Home");}

@{  Html.RenderAction("RenderFeatured", "Home");}

 @{ Html.RenderAction("RenderPostList", "Blog", new { numberOfItems = 3 });}

@{  Html.RenderAction("RenderTestimonials", "Home");}

NewGood/Views/Products.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            <li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>
        </ol>

      <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="/images/carousel/veggies-carousel.jpg" alt="Veggies" width="460" height="245">
            </div>

            <div class="item">
              <img src="/images/carousel/honey-carousel.jpg" alt="Honey" width="460" height="245">
            </div>

            <div class="item">
              <img src="/images/carousel/fruits-carousel.jpg" alt="Fruits" width="460" height="245">
            </div>

            <div class="item">
              <img src="/images/carousel/flour-carousel.jpg" alt="Flour" width="460" height="245">
            </div>
            <div class="item">
              <img src="/images/carousel/porridge-carousel.jpg" alt="porridge" width="460" height="245">
            </div>
              <div class="item">
              <img src="/images/carousel/oils-carousel.jpg" alt="porridge" width="460" height="245">
            </div>
        </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
	<div id="fh5co-work-section">
		<div class="container">
			@{ Html.RenderAction("RenderTitle", "SiteLayout");}
			<div class="row">
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/background.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

NewGood/Views/Search.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
    var searchQuery = Request.QueryString["q"];
}
<div id="fh5co-about-section">
    <div class="container">
        @{ Html.RenderAction("RenderTitle", "SiteLayout");}
        <div class="row">
            <div class="col-md-12">
                <div class="search-container">
                    <form action="/search/" method="GET" id="search">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 mx-auto">
                                <div class="form-group controls">
                                    <input type="text" class="form-control col-cx-6" placeholder="Search for something...." name="q" value="" />
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 mx-auto">
                                <div class="form-group">
                                    <button class="btn btn-primary search-button">Search <i class="fa fa-search"></i></button>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 mx-auto">
                                @if (!string.IsNullOrEmpty(searchQuery))
                                {
                                    var results = Umbraco.ContentQuery.Search(searchQuery);
                                    long resultCount = results != null && results.Any() ? results.Count() : 0;
                                    <p>Your search for <strong>@searchQuery</strong> found <strong>@resultCount</strong> result@(resultCount == 1 ? null : "s")</p>

                                       if (resultCount > 0)

                                        {
                                            foreach (var result in results)
                                            {
                                                var title = result.GetPropertyValue<string>("title");
                                                var subtitle = result.GetPropertyValue<string>("subtitle");
                                                <div>
                                                    <a href="@result.Url">
                                                        <h1 class="post-title">
                                                            @(!string.IsNullOrEmpty(title) ? title : result.Name)
                                                        </h1>
                                                        
                                                            @if (!string.IsNullOrEmpty(subtitle))
                                                            {
                                                        <h3 class="post-subtitle">@Html.Raw(@subtitle)</h3>
                                                            }   
                                                    </a>
                                                </div>
                                            }
                                        }
                                }
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

NewGood/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Good4you</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Good4you responsive website" />
    <meta name="keywords" content="healthy food diet organic" />
    <meta name="author" content="kasiakor" />

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="icon" type="image/png" href="/images/favicon-96x96.png" sizes="32x32" />

    <link href='https://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,900' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Simple Line Icons -->
    <link rel="stylesheet" href="/css/simple-line-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- Carousel glyphicon style  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="/css/style.css">


    <!-- Modernizr JS -->
    <script src="/scripts/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div id="fh5co-page">
        @{  Html.RenderAction("RenderHeader" , "SiteLayout");}

        @RenderBody()
      
        @{  Html.RenderAction("RenderFooter", "SiteLayout");}
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>



    <!-- jQuery -->
    <script src="/scripts/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="/scripts/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="/scripts/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="/scripts/jquery.waypoints.min.js"></script>
    <!-- MAIN JS -->
    <script src="/scripts/main.js"></script>

</body>
</html>